Feature/delete
Steffen-Anslinger/DIY-App pull request #20
Opened 2024-01-24 09:09 UTC by Steffen-Anslinger

2024-01-24 12:21 UTC, Roland-Hufnagel requested changes
Hey team. You did a lot of good work so far. 💪

It took some time to get familiar with your code and I was struggling with some structure and names. I recommend not to name the component 'DetailsPage'. I expect a 'page' to be in the pages folder. Like you do the import: `import ProjectDetails from "@/components/DetailsPage";` it's a good idea to name the component 'ProjectDetails'. 

You do a lot of work inside this component. The better way is to use the router and do the fetch in the page (pages/projects/[id].js). 

I see a navigation component on every page. Thats really redundant. I think the navigation should be on every page, or not? How can you apply this?

Take a look at the comments and try to improve your code a bit.

2024-01-24 12:21 UTC, Roland-Hufnagel commented on components/DetailsPage/index.js
> +          <button type="button" onClick={handleSubmit(handleDeleteProject)}>
And I am wondering, why do you use the useForm hook here and passing the props to the EditForm Component. I think a better way is to use the hook inside that component.

2024-01-24 12:21 UTC, Roland-Hufnagel commented on components/DetailsPage/index.js
> +      mutate("/api/projects", response.json());
I recommend a bit of error handling. What if deleting is not possible? You should at least test the `response.ok` value.

2024-01-24 12:21 UTC, Roland-Hufnagel commented on pages/api/projects/[id].js
> +    await Project.findByIdAndDelete(id);
You should implement some error handling here as well.

2024-01-24 15:56 UTC, moonwave99 requested changes

2024-01-24 15:56 UTC, moonwave99 commented on components/EditForm/index.js
> +    const response = await fetch(`/api/projects/${id}`);
Why the second fetch?

2024-01-25 09:20 UTC, Roland-Hufnagel approved these changes
This looks fine now. Good refactoring. 💪I just mentioned two small things.

2024-01-25 09:20 UTC, Roland-Hufnagel commented on components/EditForm/index.js
> +    }
What happens if the response is not ok?

2024-01-25 09:20 UTC, Roland-Hufnagel commented on pages/api/projects/[id].js
> +    if (!deletedProject) {
`else` would be fine

2024-01-25 10:55 UTC, merged